# Generated by Django 6.0.1 on 2026-01-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, help_text='Override author name for display purposes', max_length=255),
        ),
    ]
