# Generated by Django 6.0.1 on 2026-02-01 09:02

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.get_file_path, validators=[core.validators.validate_file_size]),
        ),
    ]
