# Generated by Django 6.0.1 on 2026-02-01 09:02

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to=core.utils.get_file_path, validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.get_file_path, validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.get_file_path, validators=[core.validators.validate_large_file_size]),
        ),
    ]
