# Generated by Django 6.0.1 on 2026-01-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcamp',
            old_name='details',
            new_name='description',
        ),
    ]
